led.enable(false)
pins.analogWritePin(AnalogPin.P2, 1023)
pins.analogWritePin(AnalogPin.P3, 1023)
pins.analogWritePin(AnalogPin.P4, 1023)
basic.forever(function () {
    pins.analogWritePin(AnalogPin.P2, 0)
    basic.pause(1000)
    pins.analogWritePin(AnalogPin.P2, 1023)
    pins.analogWritePin(AnalogPin.P3, 0)
    basic.pause(1000)
    pins.analogWritePin(AnalogPin.P3, 1023)
    pins.analogWritePin(AnalogPin.P4, 0)
    basic.pause(1000)
    pins.analogWritePin(AnalogPin.P4, 1023)
    pins.analogWritePin(AnalogPin.P3, 0)
})
